apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secureops-crm.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: {{ include "secureops-crm.fullname" . }}-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secureops-crm.fullname" . }}-db-secret
                  key: password
