# Values for secureops-crm
replicaCount: 1

image:
  repository: secureops-crm
  pullPolicy: IfNotPresent
  tag: "latest"

backend:
  replicaCount: 1
  image:
    repository: secureops-crm-backend
    tag: "latest"
    pullPolicy: IfNotPresent
    APP_ENV: production
    DB_CONNECTION: pgsql
    appKey: "base64:uS6yU4I/8fVlvTzL7zN/BqH6v2T4zJv7N7tC8T3A9Y8="
  service:
    type: ClusterIP
    port: 80

frontend:
  replicaCount: 1
  image:
    repository: secureops-crm-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

database:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine"
  auth:
    database: secureops
    username: admin
    password: secret_password_change_me

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: secureops.local
      paths:
        - path: /
          pathType: Prefix
